title: PianoSprout
description: Turn device into a magic piano! No skills needed. Just tap the highlighted keys, and our smart engine handles the rhythm for you.
theme: jekyll-theme-cayman
show_downloads: false
plugins:
  - jekyll-seo-tag
